# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - script: ls
    displayName: "what is here"

  - script: npm run dev
    displayName: "devit itpu"


  - script: npx cypress run --record --key "befeb5d3-d92f-4361-918a-057fb5e57d65"
    displayName: "lets record"
